source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yunhaiwu/ios-wj-framework-cocoapods-specs.git'

platform :ios, '7.0'

#use_frameworks!

inhibit_all_warnings!

target :'Hulk' do


pod 'WJCommon'


end
